### ISSUE TITLE
[Tech Discuss] SQL SGBD

### ISSUE THREAD

**Issue by linzera** [leotome/cienciascrapper#1]
You decided to use the MS SQL Server on this project. Is there any particular reason to use it instead of PGSQL or MySQL?

**Comment by leotome** [comment]
We found it to be more stable for the amount of data being transactioned, and better to integrate on a Microsoft based ecosystem.

On 15 Jul 2022, at 16:28, linzera ***@***.***> wrote:

﻿

You decided to use the MS SQL Server on this project. Is there any particular reason to use it instead of PGSQL or MySQL?
